USE DATABASE RETAIL_AI;
USE SCHEMA RETAIL;

CREATE OR REPLACE VIEW 
VW_CUSTOMERS AS
SELECT DISTINCT
      CUSTOMER_ID,
      CUSTOMER_NAME,
      LAST_NAME,
      DATE_OF_BIRTH,
      SEGMENT
FROM STORE_DATA;

CREATE OR REPLACE VIEW
VW_PRODUCTS AS
SELECT DISTINCT
      PRODUCT_ID,
      PRODUCT_NAME,
      CATEGORY_OF_GOODS,
      "Sub-Category" AS
SUB_CATEGORY
FROM STORE_DATA;

CREATE OR REPLACE VIEW VW_SALES 
AS SELECT
      ORDER_ID,
      CUSTOMER_ID,
      PRODUCT_ID,
      SALES,
      QUANTITY,
      DISCOUNT,
      PROFIT,
      ORDER_DATE,
      SALES_DATE,
      SHIP_DATE,
      SHIP_MODE
FROM STORE_DATA;

CREATE OR REPLACE VIEW VW_OUTLETS
AS SELECT DISTINCT
    OUTLET_TYPE,
    CITY_TYPE,
    REGION,
    STATE,
    COUNTRY,
    POSTAL_CODE
FROM STORE_DATA;



