USE DATABASE RETAIL_AI;
USE SCHEMA RETAIL;

CREATE OR REPLACE VIEW 
METRIC_TOTAL_SALES AS 
SELECT
    SUM(SALES) AS METRIC_TOTAL_SALES
FROM STORE_DATA;

CREATE OR REPLACE VIEW 
METRIC_TOTAL_PROFIT AS 
SELECT
    SUM(PROFIT) AS TOTAL_PROFIT
FROM STORE_DATA;

CREATE OR REPLACE VIEW 
METRIC_TOTAL_ORDERS AS 
SELECT
    COUNT(DISTINCT ORDER_ID) AS 
TOTAL_ORDERS
FROM STORE_DATA;

CREATE OR REPLACE VIEW 
METRIC_AVG_ORDER_VALUE AS 
SELECT
    SUM(SALES)/
    COUNT(DISTINCT ORDER_ID)
AS AVG_ORDER_VALUE
FROM STORE_DATA;

CREATE OR REPLACE VIEW
METRIC_PROFIT_MARGIN AS
SELECT 
ROUND(SUM(PROFIT)*100.0/SUM(SALES),2)
AS PROFIT_MARGIN_PERCENT
FROM STORE_DATA;

CREATE OR REPLACE VIEW 
METRIC_CATEGORY_SALES AS
SELECT CATEGORY_OF_GOODS,
SUM(SALES) AS TOTAL_SALES,
SUM(PROFIT) AS TOTAL_PROFIT
FROM STORE_DATA
GROUP BY CATEGORY_OF_GOODS;

CREATE OR REPLACE VIEW
METRIC_REGION_SALES AS SELECT REGION,
SUM(SALES) AS SALES,
SUM(PROFIT) AS PROFIT
FROM STORE_DATA 
GROUP BY REGION;

CREATE OR REPLACE VIEW
METRIC_OULET_PERFORMANCE AS SELECT OUTLET_TYPE,
SUM(SALES) AS SALES,
SUM(PROFIT) AS PROFIT
FROM STORE_DATA 
GROUP BY OUTLET_TYPE;

CREATE OR REPLACE VIEW 
METRIC_MONTHLY_SALES AS SELECT 
YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH,
SUM(SALES) AS SALES,
SUM(PROFIT) AS PROFIT
FROM STORE_DATA
GROUP BY YEAR(SALES_DATE),
MONTH(SALES_DATE)
ORDER BY YEAR,MONTH;
