SELECT DATABASE RETAIL_AI;
USE SCHEMA RETAIL;

SEELCT COUNT(*) FROM STORE_DATA;
SELECT * FROM STORE_DATA LIMIT 5;
SELECT * FROM VW_CUSTOMERS LIMIT 5;
SELECT * FROM VW_PRODUCTS LIMIT 5;
SELECT * FROM VW_SALES LIMIT 5;
SELECT * FROM VW_OUTLETS LIMIT 5;
SELECT 
SUM(SALES) AS TOTAL_SALES,
SUM(PROFIT) AS TOTAL_PROFIT,
FROM STORE_DATA;